Repository vention-js-lab/ventioners-stayhub-frontend, pull requests merged in 2024-12, with the labels that each got.

#26 feat: integrate detail page with api
  src/modules/home/api/get-accommodation.ts
  src/modules/home/api/post-wishlist.ts
  src/modules/home/components/header/index.tsx
  src/modules/home/components/single-property/property-review-card.tsx
  src/modules/home/routes/single-property.route.styles.ts
  src/modules/home/routes/single-property.route.tsx
  src/modules/home/types/accommodation.type.ts
Labels: enhancement

#27 [FEAT-55]: Added ci/cd for deployment
  .github/workflows/deploy.yml
  src/utils/getFirstErrorMessage.util.ts
Labels: enhancement

#28 [FEAT-59]: Implemented Infinite Scrolling and Added Skeletons for properties
  package-lock.json
  package.json
  src/modules/home/api/get-properties.ts
  src/modules/home/components/info-message-box/info-message-box.styles.ts
  src/modules/home/components/info-message-box/info-message-box.tsx
  src/modules/home/components/property/property-card.styles.ts
  src/modules/home/components/property/property-card.tsx
  src/modules/home/components/property/property-list.tsx
  src/modules/home/routes/home.route.tsx
  src/modules/home/skeletons/property-card.skeleton.styles.ts
  src/modules/home/skeletons/property-card.skeleton.tsx
  src/modules/home/skeletons/property-list.skeleton.tsx
Labels: enhancement

#29 fix: header responsivenes
  src/assets/logo-full.svg
  src/modules/home/components/header/index.tsx
  src/modules/home/components/header/styles/user-navigation.styles.ts
  src/modules/home/components/header/user-navigation.menu.tsx
  src/modules/home/routes/home.route.styles.ts
Labels: bug

#34 [FEAT-62]: Added lazy loading for images and blurhash
  package-lock.json
  package.json
  src/modules/home/components/lazy-image/lazy-image.tsx
  src/modules/home/components/property/property-card.tsx
  src/modules/home/components/single-property/single-property-wrapper.styles.ts
  src/modules/home/types/image.type.ts
Labels: enhancement

#30 feat(61): accommodation guests count & accommodation form rewrite
  src/assets/minus.svg
  src/assets/plus.svg
  src/main.tsx
  src/modules/home/api/create-accommodation.ts
  src/modules/home/components/create-accommodation/accommodation-details-form.tsx
  src/modules/home/components/create-accommodation/create-accommodation.tsx
  src/modules/home/components/create-accommodation/image-uploader.tsx
  src/modules/home/components/create-accommodation/styles/accommodation-details-form.styles.ts
  src/modules/home/components/header/user-navigation.menu.tsx
  src/modules/home/components/header/user-profile-picture/user-profile-picture.styles.ts
  src/modules/home/components/header/user-profile-picture/user-profile-picture.tsx
  src/modules/home/components/map/mapComponent.tsx
  src/modules/home/components/property/property-card.tsx
  src/modules/home/components/single-property/single-property-amenity.tsx
  src/modules/home/contexts/accommodation.context.tsx
  src/modules/home/contexts/index.ts
  src/modules/home/routes/create-acccommodation.route.tsx
  src/modules/home/routes/single-property.route.tsx
  src/modules/home/temp-data/single-accommodation.ts
  src/modules/home/types/accommodation-form-data.interface.ts
  src/modules/home/types/accommodation.type.ts
  src/modules/users/api/update-user-info.ts
  src/modules/users/components/delete-account-modal/delete-account-modal.tsx
  src/modules/users/routes/profile.route.tsx
  src/redux/auth/auth.slice.ts
  src/redux/store.ts
  src/routes/layout-protected.route.tsx
  src/styles/root.css
  src/zod/accommodation-create.schema.ts
  src/zod/index.ts
Labels: bug, enhancement, conflict

#37 [FIX]: Added hardcoded temp value for blurhash
  src/modules/home/components/lazy-image/lazy-image.tsx
Labels: bug

#39 [FEAT-74] Booking cancellation
  src/modules/bookings/api/cancel-booking.ts
  src/modules/bookings/api/create-booking.ts
  src/modules/bookings/api/get-bookings.ts
  src/modules/bookings/components/booking-card.styles.ts
  src/modules/bookings/components/booking-card.tsx
  src/modules/bookings/components/cancel-booking-modal.tsx
  src/modules/bookings/components/cancel-booking.modal.style.ts
  src/modules/bookings/constants/endpoints.constant.ts
  src/modules/home/constants/endpoints.constant.ts
  src/types/api-error-response.type.ts
Labels: enhancement

#43 [FIX]: Added default value for blurhash
  src/modules/home/components/property/property-card.tsx
Labels: enhancement

#45 [FIX]: Property images order fixed
  src/modules/home/components/property/property-card.tsx
  src/modules/home/components/single-property/single-property-images.route.tsx
  src/modules/home/components/single-property/single-property-wrapper.tsx
  src/modules/home/routes/single-property.route.tsx
Labels: enhancement

#47 booking error mesage has been updated
  src/modules/bookings/api/create-booking.ts
Labels: bug

#51 [FIX]: Updated icon map for new category names
  src/modules/home/constants/category-icon-map.constant.ts
Labels: bug

#53 [FIX-82]: Improved Category Styling
  public/locales/en/owner-properties.json
  public/locales/ru/owner-properties.json
  src/constants/translation-keys.constant.ts
  src/modules/home/components/category/category-item.styles.ts
  src/modules/home/components/category/category-item.tsx
  src/modules/home/components/icon/icon-wrapper.tsx
  src/modules/home/components/info-message-box/info-message-box.styles.ts
  src/modules/home/components/map/mapModal.style.ts
  src/modules/home/routes/home.route.tsx
  src/modules/owner/components/owner-property/owner-properties-list.styles.ts
  src/modules/owner/components/owner-property/owner-properties-list.tsx
  src/modules/owner/components/owner-property/owner-property-card.tsx
Labels: enhancement

#54 [FIX]: Made details page public and fixed toast message
  src/modules/bookings/api/create-booking.ts
  src/routes/private.route.ts
  src/routes/public.route.ts
Labels: bug

#59 [FIX]: Update property card skeleton size
  src/modules/home/skeletons/property-card.skeleton.styles.ts
  src/modules/home/skeletons/property-card.skeleton.tsx
Labels: bug, enhancement

#60 [FIX-87]: Fixed Booking dates and toast error messages
  public/locales/en/accommodation-details.json
  public/locales/ru/accommodation-details.json
  src/constants/translation-keys.constant.ts
  src/modules/bookings/api/create-booking.ts
  src/modules/bookings/types/create-booking.type.ts
  src/modules/property-detail/routes/single-property.route.tsx
Labels: bug, enhancement

#61 rounded to numbers from decimal on total price and service fee
  src/modules/property-detail/component/single-property-amenity.tsx
Labels: bug

#68 sceleton for category
  src/modules/home/components/category/category-item.tsx
  src/modules/home/components/category/category-list.tsx
Labels: bug

#69 [FIX-94]: Update styles for owner property card
  src/modules/owner/components/owner-property/owner-property-card.styles.ts
  src/modules/owner/components/owner-property/owner-property-card.tsx
Labels: bug, enhancement

#71 [FIX-90]: Updated incorrect price calculation in booking card
  src/modules/property-detail/component/single-property-amenity.tsx
Labels: bug
