Repository vention-js-lab/ventioners-stayhub-frontend, pull requests merged in 2024-11, with the labels that each got.

#4 [IT][18]feat: add PropertyList with some dummy data
  src/modules/home/components/property/dummy.json
  src/modules/home/components/property/index.tsx
  src/modules/home/components/property/propertyCard.tsx
  src/modules/home/routes/home.route.tsx
Labels: enhancement

#5 [DJ][12]: Added categories component for home page
  package.json
  src/modules/home/components/category/category-item.styles.ts
  src/modules/home/components/category/category-item.tsx
  src/modules/home/components/category/category-list.styles.ts
  src/modules/home/components/category/category-list.tsx
  src/modules/home/components/category/category-scroll-arrow.styles.ts
  src/modules/home/components/category/category-scroll-arrow.tsx
  src/modules/home/components/property/index.tsx
  src/modules/home/constants/colors.constant.ts
  src/modules/home/data/category-data.ts
  src/modules/home/routes/home.route.styles.ts
  src/modules/home/routes/home.route.tsx
  src/modules/home/types/category-with-icon.type.ts
  src/types/mui-styles-object.type.ts
Labels: enhancement

#6 [IT]:[17-Property-Card] feat: property card component has been created
  package-lock.json
  package.json
  src/modules/home/components/property/dummy.json
  src/modules/home/components/property/property.styles.ts
  src/modules/home/components/property/propertyCard.tsx
  src/modules/home/components/property/swiper.css
Labels: enhancement

#8 [DJ][FEAT-19]: Integrate accommodation api with frontend
  src/modules/home/api/get-properties.ts
  src/modules/home/components/category/category-list.tsx
  src/modules/home/components/property/index.tsx
  src/modules/home/components/property/property-card.tsx
  src/modules/home/constants/endpoints.constant.ts
  src/modules/home/hooks/use-search-params-state.ts
  src/modules/home/routes/home.route.tsx
  src/modules/home/types/accommodation.type.ts
  src/types/swiper.d.ts
Labels: enhancement

#12 [FEAT-36]: header linting errors fixed
  src/modules/home/components/header/constants/guest-types.constant.ts
  src/modules/home/components/header/constants/index.ts
  src/modules/home/components/header/constants/languages.constant.ts
  src/modules/home/components/header/index.tsx
  src/modules/home/components/header/modals/calendar.modal.tsx
  src/modules/home/components/header/modals/guests.modal.tsx
  src/modules/home/components/header/modals/index.ts
  src/modules/home/components/header/modals/language.modal.tsx
  src/modules/home/components/header/search-bar.tsx
  src/modules/home/components/header/styles/guest-modal.styles.ts
  src/modules/home/components/header/styles/index.ts
  src/modules/home/components/header/styles/language-modal.styles.ts
  src/modules/home/components/header/styles/user-navigation.styles.ts
  src/modules/home/components/header/user-navigation.menu.tsx
  src/modules/home/styles/header/counter-button.ts
  src/modules/home/styles/header/counter-text.ts
  src/modules/home/styles/header/day-button.ts
  src/modules/home/styles/header/divider.ts
  src/modules/home/styles/header/index.ts
  src/modules/home/styles/header/nav-button.ts
  src/modules/home/styles/header/search-button.ts
  src/modules/home/styles/header/search-section.ts
  src/modules/home/styles/header/searchbar-container.ts
  src/modules/home/styles/header/user-menu.ts
  src/modules/home/styles/header/weekly-label.ts
  src/modules/home/types/enums/index.ts
  src/modules/home/types/enums/lang.enum.ts
Labels: conflict

#13 [DJ][FEAT-30]: Added icon map for categories and integration with backend
  package-lock.json
  package.json
  src/modules/home/api/get-categories.ts
  src/modules/home/components/category/category-item.styles.ts
  src/modules/home/components/category/category-item.tsx
  src/modules/home/components/category/category-list.tsx
  src/modules/home/components/icon/icon-wrapper.tsx
  src/modules/home/constants/category-icon-map.constant.ts
  src/modules/home/constants/endpoints.constant.ts
  src/modules/home/data/category-data.ts
  src/modules/home/types/category-with-icon.type.ts
  src/modules/home/types/category.type.ts
  src/modules/home/types/icon.type.ts
Labels: enhancement

#11 [AM][REFACTOR-27][FEAT-36]: Fix lint errors, rewrite styles
  src/configs/axios.config.ts
  src/modules/auth/components/login/components/email-input.tsx
  src/modules/auth/components/login/components/email-input/email-input.module.css
  src/modules/auth/components/login/components/email-input/email-input.tsx
  src/modules/auth/components/login/components/index.ts
  src/modules/auth/components/login/components/password-input.tsx
  src/modules/auth/components/login/components/password-input/password-input.module.css
  src/modules/auth/components/login/components/password-input/password-input.tsx
  src/modules/auth/components/login/login-form/login-form.module.css
  src/modules/auth/components/login/login-form/login-form.styles.ts
  src/modules/auth/components/login/login-form/login-form.tsx
  src/modules/auth/components/shared/basic-input/basic-input.tsx
  src/modules/auth/components/shared/error-message/error-message.module.css
  src/modules/auth/components/shared/error-message/error-message.styles.ts
  src/modules/auth/components/shared/error-message/error-message.tsx
  src/modules/auth/components/shared/google-auth-button/google-auth-button.module.css
  src/modules/auth/components/shared/google-auth-button/google-auth-button.styles.ts
  src/modules/auth/components/shared/google-auth-button/google-auth-button.tsx
  src/modules/auth/components/shared/index.ts
  src/modules/auth/components/shared/submit-button/submit-button.tsx
  src/modules/auth/components/signup/components/confirm-password-input.tsx
  src/modules/auth/components/signup/components/confirm-password-input/confirm-password-input.module.css
  src/modules/auth/components/signup/components/confirm-password-input/confirm-password-input.tsx
  src/modules/auth/components/signup/components/email-input.tsx
  src/modules/auth/components/signup/components/email-input/email-input.module.css
  src/modules/auth/components/signup/components/email-input/email-input.tsx
  src/modules/auth/components/signup/components/first-name-input.tsx
  src/modules/auth/components/signup/components/first-name-input/first-name-input.module.css
  src/modules/auth/components/signup/components/first-name-input/first-name-input.tsx
  src/modules/auth/components/signup/components/index.ts
  src/modules/auth/components/signup/components/last-name-input.tsx
  src/modules/auth/components/signup/components/last-name-input/last-name-input.module.css
  src/modules/auth/components/signup/components/last-name-input/last-name-input.tsx
  src/modules/auth/components/signup/components/password-input.tsx
  src/modules/auth/components/signup/components/password-input/password-input.module.css
  src/modules/auth/components/signup/components/password-input/password-input.tsx
  src/modules/auth/components/signup/signup-form/signup-form.module.css
  src/modules/auth/components/signup/signup-form/signup-form.styles.ts
  src/modules/auth/components/signup/signup-form/signup-form.tsx
  src/modules/auth/constants/index.ts
  src/modules/auth/constants/styles.constant.ts
  src/modules/auth/routes/login.route.tsx
  src/modules/auth/routes/signup.route.tsx
  src/modules/auth/styles/auth-page.module.css
  src/modules/auth/styles/auth-page.styles.ts
  src/modules/auth/styles/input.styles.ts
  src/modules/auth/types/form-data.ts
  src/modules/auth/types/index.ts
  src/modules/auth/utils/index.ts
  src/modules/auth/utils/is-input-field-empty.util.ts
  src/utils/get-first-error-message.util.ts
  src/zod/user-login.schema.ts
  src/zod/user-signup.schema.ts
Labels: question

#15 [D][FEAT-40]: Added Wishlist page and Refactored Property and Header components
  src/modules/home/api/get-wishlisted-properties.ts
  src/modules/home/components/header/index.tsx
  src/modules/home/components/header/menu-item-link.tsx
  src/modules/home/components/header/user-navigation.menu.tsx
  src/modules/home/components/property/index.tsx
  src/modules/home/components/property/property-card.styles.ts
  src/modules/home/components/property/property-card.tsx
  src/modules/home/components/property/property-list.styles.ts
  src/modules/home/components/property/property-list.tsx
  src/modules/home/constants/endpoints.constant.ts
  src/modules/home/index.tsx
  src/modules/home/routes/home.route.tsx
  src/modules/home/routes/wishlist.route.styles.ts
  src/modules/home/routes/wishlist.route.tsx
Labels: enhancement

#20 feat[34]: authentication check, improved header
  eslint.config.js
  package-lock.json
  package.json
  src/assets/google.svg
  src/assets/mail.svg
  src/configs/axios.config.ts
  src/main.tsx
  src/modules/auth/components/login/login-form/login-form.tsx
  src/modules/auth/components/shared/auth-redirect-button/auth-redirect-button.styles.ts
  src/modules/auth/components/shared/auth-redirect-button/auth-redirect-button.tsx
  src/modules/auth/components/shared/google-auth-button/google-auth-button.tsx
  src/modules/auth/components/shared/index.ts
  src/modules/auth/components/signup/signup-form/signup-form.tsx
  src/modules/auth/constants/endpoints.constant.ts
  src/modules/auth/hooks/index.ts
  src/modules/auth/hooks/use-auth.ts
  src/modules/auth/styles/auth-page.styles.ts
  src/modules/auth/types/form-data.ts
  src/modules/home/api/get-categories.ts
  src/modules/home/api/get-properties.ts
  src/modules/home/api/get-wishlisted-properties.ts
  src/modules/home/components/header/destination-search.tsx
  src/modules/home/components/header/index.tsx
  src/modules/home/components/header/styles/search-bar.styles.ts
  src/modules/home/components/header/styles/user-navigation.styles.ts
  src/modules/home/components/header/user-navigation.menu.tsx
  src/modules/home/components/header/user-profile-icon.tsx
  src/modules/home/components/property/property-card.tsx
  src/modules/home/constants/endpoints.constant.ts
  src/modules/home/index.tsx
  src/modules/home/styles/header/nav-button.ts
  src/modules/home/styles/header/search-section.ts
  src/modules/home/styles/index.ts
  src/modules/home/types/enums/index.ts
  src/modules/home/types/enums/lang.enum.ts
  src/redux/auth/auth-slice.ts
  src/redux/hooks.ts
  src/redux/store.ts
  src/routes/layout-protected.route.tsx
  src/routes/router.tsx
  src/styles/index.ts
  src/styles/layout-protected.styles.ts
  src/types/index.ts
  src/types/user.type.ts
  src/zod/user-login.schema.ts
  src/zod/user-signup.schema.ts
Labels: enhancement

#21 39 accommodation detail
  package-lock.json
  package.json
  src/modules/home/components/header/index.tsx
  src/modules/home/components/property/property-card.tsx
  src/modules/home/components/single-property/property-review-card.tsx
  src/modules/home/components/single-property/single-property-amenity.styles.ts
  src/modules/home/components/single-property/single-property-amenity.tsx
  src/modules/home/components/single-property/single-property-images.route.tsx
  src/modules/home/components/single-property/single-property-review.styles.ts
  src/modules/home/components/single-property/single-property-review.tsx
  src/modules/home/components/single-property/single-property-wrapper.styles.ts
  src/modules/home/components/single-property/single-property-wrapper.tsx
  src/modules/home/constants/price.constant.ts
  src/modules/home/constants/staying-days.constant.ts
  src/modules/home/index.tsx
  src/modules/home/routes/single-property.route.styles.ts
  src/modules/home/routes/single-property.route.tsx
  src/modules/home/temp-data/single-accommodation.ts
  src/types/amenity.types.ts
  src/utils/truncate-string.util.ts
Labels: enhancement, conflict

#17 [FE] 43-wishlist added
  src/modules/home/api/post-wishlist.ts
  src/modules/home/components/property/dummy.json
  src/modules/home/components/property/property-card.tsx
  src/modules/home/components/property/property-list.tsx
  src/modules/home/types/accommodation.type.ts
  src/utils/getFirstErrorMessage.util.ts
Labels: enhancement, conflict

#22 Created map component
  .env.example
  package-lock.json
  package.json
  src/modules/home/components/map/mapComponent.style.ts
  src/modules/home/components/map/mapComponent.tsx
  src/modules/home/routes/home.route.styles.ts
  src/modules/home/routes/home.route.tsx
Labels: draft
